### ISSUE TITLE
listfields causing 'NoneType' object has no attribute 'choices'

### ISSUE THREAD

**Issue by wags007** [jschrewe/django-mongodbforms#13]
Exception Type:     AttributeError
Exception Value:    'NoneType' object has no attribute 'choices'

I am trying to use mongoadmin-0.1.3-py2.7 which is dependent on this package.  The only issue I have so far is the error above on any of my models with listfields.

Here is an example of my model:
class packageInfo( Document ):
    dateAdded = DateTimeField()
    dateLastEdited = DateTimeField()
    serverUUID = StringField(required=True)
    packageList = ListField()

```
class Meta:
    using = 'mongodb'
```

The line it doesn't like is 161 in 
https://github.com/jschrewe/django-mongodbforms/blob/master/mongodbforms/documents.py
Which reads like this:

 if isinstance(f, ListField) and not (f.field.choices or isinstance(f.field, ReferenceField)):
            continue

I was going to submit a patch but I am not sure what use case would match the f.field.choices field properly.  If I am doing it wrong please let me know.  I am still new to Mongodb and making it work with django.
Thanks
Brian

**Comment by chapayevdauren** [comment]
Hi! I have same error here

`Exception Type: AttributeError at *
Exception Value: 'NoneType' object has no attribute 'choices'`

Django (1.7.4)
mongoadmin (0.2)
mongodbforms (0.3.1)
mongoengine (0.8.7)

class Donation(me.Document):
    user = me.ReferenceField(
        User, dbref=False, required=True,
        reverse_delete_rule=NULL_OR_DENY,
        help_text=_("Donation giver"))
    name = me.StringField(help_text=_("Giver name"))
    mobile = me.StringField(help_text=_("Giver mobile"))
    address = me.StringField(help_text=_("Giver address"))
    description = me.StringField(help_text=_("Donation description"))
    lonlat = me.ListField(
         required=True,
         help_text=_("Array object of longitude and latitude"))
    images = me.ListField(help_text=_("User uploads"))
    ts = me.DateTimeField(default=timezone.now)
